---
title: "DataquestProject_COVID19_Virus_Trends"
output: html_document
authour: Ba Linh Le
---

```{r setup, includ e= FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tibble)
library(dplyr)
```

```{r data exploration}
covid_df <- read.csv("covid19.csv")

dim(covid_df)
vector_cols <- colnames(covid_df)
vector_cols

head(covid_df)
glimpse(covid_df)
```

```{r data cleaning using base R}
covid_df_all_states <- covid_df[covid_df$Province_State == "All States", !(colnames(covid_df)) == "Province_State"]

covid_df_all_states_daily <- covid_df_all_states[c("Date", "Country_Region", "active", "hospitalizedCurr", "daily_tested", "daily_positive")]

covid_df_all_states_daily_sum <- aggregate(cbind(daily_tested, daily_positive, active, hospitalizedCurr) ~ Country_Region, data = covid_df_all_states_daily, sum, na.rm = TRUE)

covid_df_all_states_daily_sum <- covid_df_all_states_daily_sum[order(covid_df_all_states_daily_sum$tested, decreasing = TRUE),]
covid_top_10 <- covid_df_all_states_daily_sum[1:10,]

countries <- covid_top_10$Country_Region
tested_cases <- covid_top_10$tested
positive_cases <- covid_top_10$positive
active_cases <- covid_top_10$active
hospitalized_cases <- covid_top_10$hospitalized

x <- sapply(list(tested_cases, positive_cases, active_cases, hospitalized_cases), setNames, countries)

positive_tested_top_3 <- x[,2]/x[,1]
positive_tested_top_3 <- positive_tested_top_3[order(positive_tested_top_3, decreasing = TRUE)]
positive_tested_top_3 <- positive_tested_top_3[1:3]
```


```{r data cleaning using dplyr}
covid_df_all_states <- covid_df %>%
  filter(Province_State == "All States") %>% 
  select(-Province_State)

covid_df_all_states_daily <- covid_df_all_states %>% 
  select(Date, Country_Region, active, hospitalizedCurr, daily_tested, daily_positive)

covid_df_all_states_daily_sum <- covid_df_all_states_daily %>% 
  group_by(Country_Region) %>% 
  summarise(tested = sum(daily_tested),
            positive = sum(daily_positive),
            active = sum(active),
            hospitalized = sum(hospitalizedCurr)) %>% 
  arrange(desc(tested))

covid_top_10 <- head(covid_df_all_states_daily_sum, 10)

countries <- covid_top_10$Country_Region
tested_cases <- covid_top_10$tested
positive_cases <- covid_top_10$positive
active_cases <- covid_top_10$active
hospitalized_cases <- covid_top_10$hospitalized

names(tested_cases) <- countries
names(positive_cases) <- countries
names(hospitalized_cases) <- countries
names(active_cases) <-  countries

positive_tested_top_3 <- data.frame(ratio = positive_cases/tested_cases) %>% 
  arrange(desc(ratio)) %>% 
  slice(1:3)
```